In [1]:
# Import basic packages
import numpy as np
import scipy as sp
import pandas as pd
from astropy.io import fits


# ==== Scikit-learn =======================
# Preprocessing
from sklearn.preprocessing import StandardScaler #Standar scaler for standardization
from sklearn.model_selection import train_test_split # For random split

# Classifiers
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# Metrics
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from pprint import pprint

# ==========================================
# Matplotlib, urlib etc 
import urllib
import urllib.request
import matplotlib
import matplotlib.pyplot as plt
from IPython.display import clear_output, display
from PIL import Image
%matplotlib inline

In [2]:
from sklearn.metrics import confusion_matrix

def rates(y_true, y_pred):
    CM = confusion_matrix(y_true, y_pred)

    TN = CM[0][0]
    FN = CM[1][0]
    TP = CM[1][1]
    FP = CM[0][1]
    
    # Initialize
    X_mat = np.zeros(4)
    
    # Populate
    X_mat[0] = TN
    X_mat[1] = FN
    X_mat[2] = TP
    X_mat[3] = FP
    
    return X_mat  

### Import feature matrix and labels

In [24]:
randoms = np.load("/data/des81.a/data/kherron/LSBG/trainingfiles/Randoms/X_randoms_40k_feat.npy")
randoms_l = np.load("/data/des81.a/data/kherron/LSBG/trainingfiles/Randoms/y_randoms_40k_lab.npy")


burcin = np.load("/data/des80.b/data/burcinmp/y6_lsbg/y6/test_classifier/random_forest/v3/X_mat_v4_a.npy")
burcin_l = np.load("/data/des80.b/data/burcinmp/y6_lsbg/y6/test_classifier/random_forest/v3/y_lab_v4_a.npy")


sel = (burcin_l == 1)
burcin = burcin[sel]
burcin_l = burcin_l[sel]

In [25]:
X_feat_real = np.concatenate((randoms,burcin))
y_lab_real = np.concatenate((randoms_l,burcin_l))

X_feat_y3 = np.load("/data/des81.a/data/kherron/LSBG/trainingfiles/X_mat_y3.npy") 
y_lab_y3 = np.load("/data/des81.a/data/kherron/LSBG/trainingfiles/y_lab_y3.npy")

X_feat_sim = np.load("/data/des81.a/data/kherron/LSBG/trainingfiles/X_mat_sim_clean.npy") 
y_lab_sim = np.load("/data/des81.a/data/kherron/LSBG/trainingfiles/y_lab_sim_clean.npy")

print("Number of visually inspected LSBGs: ",len(y_lab_real[y_lab_real==1]))
print("Y3 LSBGs: ",len(y_lab_y3))
print("Simulated LSBGs: ",len(y_lab_sim[y_lab_sim==1]))

Number of visually inspected LSBGs:  30475
Y3 LSBGs:  20331
Simulated LSBGs:  8154


In [59]:
np.unique(y_lab_sim)

array([1.])

In [27]:
len(X_feat_y3)

20331

In [28]:
sel = y_lab_y3 == 0
len(X_feat_y3[sel])

0

### Create the final model and evaluate the performance

In [29]:
index_real=(y_lab_real==1)
index_art=(y_lab_real==0)

X_art = X_feat_real[index_art]
X_lsbg = X_feat_real[index_real]
X_sim = X_feat_sim

y_art = y_lab_real[index_art]
y_lsbg = y_lab_real[index_real]
y_sim = y_lab_sim

X_train_art, X_test_art, y_train_art, y_test_art = train_test_split(X_art, y_art,
                                                                        train_size = 0.70, random_state = 42)
X_train_lsbg, X_test_lsbg, y_train_lsbg, y_test_lsbg = train_test_split(X_lsbg, y_lsbg,
                                                                        train_size = 0.70, random_state = 42)
X_train_sim, X_test_sim, y_train_sim, y_test_sim = train_test_split(X_sim, y_sim,
                                                                        train_size = 0.70, random_state = 42)
X_train_y3, X_test_y3, y_train_y3, y_test_y3 = train_test_split(X_feat_y3, y_lab_y3,
                                                                        train_size = 0.70, random_state = 42)

print("ARTIFACTS:",len(X_train_art), len(X_test_art))
print("Y3:",len(X_train_y3), len(X_test_y3))
print("LSBGs:",len(X_train_lsbg), len(X_test_lsbg))
print("SIMs:",len(X_train_sim), len(X_test_sim))


ARTIFACTS: 28000 12000
Y3: 14231 6100
LSBGs: 21332 9143
SIMs: 5707 2447


In [30]:
#X_train = np.concatenate((X_train_art,X_train_lsbg,X_train_y3))#,X_train_sim))
#y_train = np.concatenate((y_train_art,y_train_lsbg,y_train_y3))#,y_train_sim))

X_train = np.concatenate((X_train_art,X_train_lsbg))#,X_train_sim))
y_train = np.concatenate((y_train_art,y_train_lsbg))#,y_train_sim))

# Standardize the two sets
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

In [31]:
#Using Default
model_rf_fin = RandomForestClassifier(n_estimators=100)
#                                       criterion='entropy',
#                                       max_depth=10,
#                                       max_features=None)
#                                       min_samples_leaf=2,
#                                       min_samples_split=12)
#                                       n_estimators=240)
model_rf_fin.fit(X_train,y_train)


RandomForestClassifier()

In [32]:
print('AUC Score ={:.4f}'.format(metrics.f1_score(y_train,model_rf_fin.predict(X_train))))

AUC Score =0.9943


In [33]:
X_mat_save_a = np.concatenate((X_art,X_lsbg,X_feat_y3,X_sim))
y_lab_save_a = np.concatenate((y_art,y_lsbg,y_lab_y3,y_sim))
#np.save('X_mat_v4_a',X_mat_save_a)
#np.save('y_lab_v4_a',y_lab_save_a)

X_mat_save_b = np.concatenate((X_art,X_lsbg,X_sim))
y_lab_save_b = np.concatenate((y_art,y_lsbg,y_sim))
#np.save('X_mat_v4_b',X_mat_save_b)
#np.save('y_lab_v4_b',y_lab_save_b)

X_mat_save_c = np.concatenate((X_art,X_lsbg,X_feat_y3))
y_lab_save_c = np.concatenate((y_art,y_lsbg,y_lab_y3))
#np.save('X_mat_v4_c',X_mat_save_c)
#np.save('y_lab_v4_c',y_lab_save_c)

X_mat_save_d = np.concatenate((X_art,X_lsbg))
y_lab_save_d = np.concatenate((y_art,y_lsbg))
#np.save('X_mat_v4_d',X_mat_save_d)
#np.save('y_lab_v4_d',y_lab_save_d)


print(len(y_lab_save_a),len(y_lab_save_b),len(y_lab_save_c),len(y_lab_save_d))

98960 78629 90806 70475


# Make Test Sample

In [34]:
# With No Simulations
X_test_10 = np.concatenate((X_test_lsbg,X_test_y3,X_test_art)) 
y_test_10 = np.concatenate((y_test_lsbg,y_test_y3,y_test_art))

# With Only Simulations
X_test_20 = np.concatenate((X_test_sim,X_test_art))
y_test_20 = np.concatenate((y_test_sim,y_test_art))

print(len(X_test_10),len(X_test_20),len(X_test_art),len(X_test_lsbg),len(X_feat_y3),len(X_test_sim))

27243 14447 12000 9143 20331 2447


### Start binning

In [35]:
x_bins = [24,25,26,27,28]
X1 = np.concatenate((X_test_lsbg,X_test_y3))
y1 = np.concatenate((y_test_lsbg,y_test_y3))
bin1 = (X1[:,16]> x_bins[0]) & (X1[:,16]< x_bins[1])
bin2 = (X1[:,16]> x_bins[1]) & (X1[:,16]< x_bins[2])
bin3 = (X1[:,16]> x_bins[2]) & (X1[:,16]< x_bins[3])
bin4 = (X1[:,16]> x_bins[3]) & (X1[:,16]< x_bins[4])
bin5 = (X1[:,16]> x_bins[4])

In [36]:
X2 = X_test_sim 
y2 = y_test_sim 
bin10 = (X2[:,16]> x_bins[0]) & (X2[:,16]< x_bins[1])
bin20 = (X2[:,16]> x_bins[1]) & (X2[:,16]< x_bins[2])
bin30 = (X2[:,16]> x_bins[2]) & (X2[:,16]< x_bins[3])
bin40 = (X2[:,16]> x_bins[3]) & (X2[:,16]< x_bins[4])
bin50 = (X2[:,16]> x_bins[4])

In [37]:
print(x_bins)
print(len(X1[bin1]),len(X1[bin2]),len(X1[bin3]),len(X1[bin4]),len(X1[bin5]))
print(len(X2[bin10]),len(X2[bin20]),len(X2[bin30]),len(X2[bin40]),len(X2[bin50]))

[24, 25, 26, 27, 28]
10388 4139 701 14 1
1012 1150 285 0 0


In [38]:
# 24 <= mu_g<=25
#Select 209 from real
X1_bin1 = X1[bin1]
y1_bin1 = y1[bin1]
X2_bin1 = X2[bin10]
y2_bin1 = y2[bin10]

all1 = np.arange(len(X1_bin1)) 
ind1 = np.random.choice(all1, size=len(X2_bin1), replace=False)

X1_test_bin1 = X1_bin1[ind1]
y1_test_bin1 =  y1_bin1[ind1]
X2_test_bin1 = X2_bin1
y2_test_bin1 =  y2_bin1

print(len(X1_test_bin1))

1012


In [39]:
# 25. <= mu_g<= 26
# Select 1186 from real
X1_bin2 = X1[bin2]
y1_bin2 = y1[bin2]
X2_bin2 = X2[bin20]
y2_bin2 = y2[bin20]

all2 = np.arange(len(X1_bin2)) 
ind2 = np.random.choice(all2, size=len(X2_bin2), replace=False)

X1_test_bin2 = X1_bin2[ind2]
y1_test_bin2 =  y1_bin2[ind2]
X2_test_bin2 = X2_bin2
y2_test_bin2 =  y2_bin2

print(len(X2_test_bin2))

1150


In [40]:
# 26. <= mu_g<= 27
# Select 1052 from real
X1_bin3 = X1[bin3]
y1_bin3 = y1[bin3]
X2_bin3 = X2[bin30]
y2_bin3 = y2[bin30]

all3 = np.arange(len(X1_bin3)) 
ind3 = np.random.choice(all3, size=len(X2_bin3), replace=False)

X1_test_bin3 = X1_bin3[ind3]
y1_test_bin3 =  y1_bin3[ind3]
X2_test_bin3 = X2_bin3
y2_test_bin3 =  y2_bin3

print(len(X1_test_bin3))

285


### Binned test set

In [41]:
#artifacts accordingly
xx1 = len(X1_test_bin1)
xx2 = len(X1_test_bin2)
xx3 = len(X1_test_bin3)
num_a1 = 20*xx1
num_a2 = 20*xx2
num_a3 = 20*xx3

all4 = np.arange(len(X_art)) 
ind4_1 = np.random.choice(all4, size=num_a1, replace=False)
ind4_2 = np.random.choice(all4, size=num_a2, replace=False)
ind4_3 = np.random.choice(all4, size=num_a3, replace=False)

X_test_art1 = X_art[ind4_1]
y_test_art1 =  y_art[ind4_1]
X_test_art2 = X_art[ind4_2]
y_test_art2 =  y_art[ind4_2]
X_test_art3 = X_art[ind4_3]
y_test_art3 =  y_art[ind4_3]

print(len(X_test_art1),len(X_test_art2),len(X_test_art3))

20240 23000 5700


In [42]:
print(xx1)

1012


In [43]:
# Only real data
X_test_bin_1 = np.concatenate((X_test_art,X1_test_bin1,X1_test_bin2,X1_test_bin3)) 
y_test_bin_1 = np.concatenate((y_test_art,y1_test_bin1,y1_test_bin2,y1_test_bin3))
# Only simulation data
X_test_bin_2 = np.concatenate((X_test_art,X2_test_bin1,X2_test_bin2,X2_test_bin3)) 
y_test_bin_2 = np.concatenate((y_test_art,y2_test_bin1,y2_test_bin2,y2_test_bin3))

X_test_bin_1 = scaler.transform(X_test_bin_1)
X_test_bin_2 = scaler.transform(X_test_bin_2)

print(len(X_test_art),len(X1_test_bin1)+len(X1_test_bin2)+len(X1_test_bin3))

12000 2447


### BIN1: 24. <= mu_g<= 25

In [44]:
# Binned test set
# Only real data
X_test_bin1_1 = np.concatenate((X_test_art1,X1_test_bin1)) 
y_test_bin1_1 = np.concatenate((y_test_art1,y1_test_bin1))
# Only simulation data
X_test_bin1_2 = np.concatenate((X_test_art1,X2_test_bin1)) 
y_test_bin1_2 = np.concatenate((y_test_art1,y2_test_bin1))

X_test_bin1_1 = scaler.transform(X_test_bin1_1)
X_test_bin1_2 = scaler.transform(X_test_bin1_2)

# Predict on the test set
y_pred_bin1_1 = model_rf_fin.predict(X_test_bin1_1)
y_pred_bin1_2 = model_rf_fin.predict(X_test_bin1_2)

print(len(X_test_art1),len(X1_test_bin1),len(X2_test_bin1))

20240 1012 1012


In [45]:
print("Precision (purity):",precision_score(y_test_bin1_1,y_pred_bin1_1))
print("Recall (completeness):",recall_score(y_test_bin1_1,y_pred_bin1_1))
print("Balanced accuracy:", balanced_accuracy_score(y_test_bin1_1,y_pred_bin1_1))

Precision (purity): 0.7396142433234422
Recall (completeness): 0.9851778656126482
Balanced accuracy: 0.9839179841897233


In [46]:
print("Precision (purity):",precision_score(y_test_bin1_2,y_pred_bin1_2))
print("Recall (completeness):",recall_score(y_test_bin1_2,y_pred_bin1_2))
print("Balanced accuracy:", balanced_accuracy_score(y_test_bin1_2,y_pred_bin1_2))

Precision (purity): 0.7419117647058824
Recall (completeness): 0.9970355731225297
Balanced accuracy: 0.9898468379446641


In [47]:
rate_bin1_1 = rates(y_test_bin1_1,y_pred_bin1_1)
rate_bin1_2 = rates(y_test_bin1_2,y_pred_bin1_2)

print("TN   FN   TP   FP")
print(rate_bin1_1)
print(rate_bin1_2)

TN   FN   TP   FP
[1.9889e+04 1.5000e+01 9.9700e+02 3.5100e+02]
[1.9889e+04 3.0000e+00 1.0090e+03 3.5100e+02]


In [48]:
TN = rate_bin1_1[0]
FN = rate_bin1_1[1]
TP = rate_bin1_1[2]
FP = rate_bin1_1[3]

# Sensitivity, hit rate, recall, or true positive rate
TPR_bin1_1 = TP/(TP+FN)
print("true positive rate:",TPR_bin1_1)
# Specificity or true negative rate
TNR_bin1_1 = TN/(TN+FP) 
print("true negative rate:",TNR_bin1_1)
# Precision or positive predictive value
PPV_bin1_1 = TP/(TP+FP)
print("positive predictive value:",PPV_bin1_1)
# Negative predictive value
NPV_bin1_1 = TN/(TN+FN)
print("negative predictive value:",NPV_bin1_1)
# Fall out or false positive rate
FPR_bin1_1 = FP/(FP+TN)
print("false positive rate:",FPR_bin1_1)
# False negative rate
FNR_bin1_1 = FN/(TP+FN)
print("false negative rate:",FNR_bin1_1)
# False discovery rate
FDR_bin1_1 = FP/(TP+FP)
print("false discovery rate:",FDR_bin1_1)

# Overall accuracy
ACC_bin1_1 = (TP+TN)/(TP+FP+FN+TN)
print("Overall accuracy:",ACC_bin1_1)

true positive rate: 0.9851778656126482
true negative rate: 0.9826581027667984
positive predictive value: 0.7396142433234422
negative predictive value: 0.999246382636656
false positive rate: 0.01734189723320158
false negative rate: 0.014822134387351778
false discovery rate: 0.2603857566765579
Overall accuracy: 0.9827780914737436


### BIN2: 25. <= mu_g<= 26

In [49]:
# Binned test set
# Only real data
X_test_bin2_1 = np.concatenate((X_test_art2,X1_test_bin2)) 
y_test_bin2_1 = np.concatenate((y_test_art2,y1_test_bin2))
# Only simulation data
X_test_bin2_2 = np.concatenate((X_test_art2,X2_test_bin2)) 
y_test_bin2_2 = np.concatenate((y_test_art2,y2_test_bin2))

X_test_bin2_1 = scaler.transform(X_test_bin2_1)
X_test_bin2_2 = scaler.transform(X_test_bin2_2)

# Predict on the test set
y_pred_bin2_1 = model_rf_fin.predict(X_test_bin2_1)
y_pred_bin2_2 = model_rf_fin.predict(X_test_bin2_2)

print(len(X_test_art2),len(X1_test_bin2),len(X2_test_bin2))

23000 1150 1150


In [50]:
print("Precision (purity):",precision_score(y_test_bin2_1,y_pred_bin2_1))
print("Recall (completeness):",recall_score(y_test_bin2_1,y_pred_bin2_1))
print("Balanced accuracy:", balanced_accuracy_score(y_test_bin2_1,y_pred_bin2_1))

Precision (purity): 0.7350260416666666
Recall (completeness): 0.9817391304347826
Balanced accuracy: 0.9820217391304348


In [51]:
print("Precision (purity):",precision_score(y_test_bin2_2,y_pred_bin2_2))
print("Recall (completeness):",recall_score(y_test_bin2_2,y_pred_bin2_2))
print("Balanced accuracy:", balanced_accuracy_score(y_test_bin2_2,y_pred_bin2_2))

Precision (purity): 0.7372498386055519
Recall (completeness): 0.9930434782608696
Balanced accuracy: 0.9876739130434783


In [52]:
rate_bin2_1 = rates(y_test_bin2_1,y_pred_bin2_1)
rate_bin2_2 = rates(y_test_bin2_2,y_pred_bin2_2)

print("TN   FN   TP   FP")
print(rate_bin2_1)
print(rate_bin2_2)

TN   FN   TP   FP
[2.2593e+04 2.1000e+01 1.1290e+03 4.0700e+02]
[2.2593e+04 8.0000e+00 1.1420e+03 4.0700e+02]


In [53]:
TN = rate_bin2_1[0]
FN = rate_bin2_1[1]
TP = rate_bin2_1[2]
FP = rate_bin2_1[3]

# Sensitivity, hit rate, recall, or true positive rate
TPR_bin2_1 = TP/(TP+FN)
print("true positive rate:",TPR_bin2_1)
# Specificity or true negative rate
TNR_bin2_1 = TN/(TN+FP) 
print("true negative rate:",TNR_bin2_1)
# Precision or positive predictive value
PPV_bin2_1 = TP/(TP+FP)
print("positive predictive value:",PPV_bin2_1)
# Negative predictive value
NPV_bin2_1 = TN/(TN+FN)
print("negative predictive value:",NPV_bin2_1)
# Fall out or false positive rate
FPR_bin2_1 = FP/(FP+TN)
print("false positive rate:",FPR_bin2_1)
# False negative rate
FNR_bin2_1 = FN/(TP+FN)
print("false negative rate:",FNR_bin2_1)
# False discovery rate
FDR_bin2_1 = FP/(TP+FP)
print("false discovery rate:",FDR_bin2_1)

# Overall accuracy
ACC_bin2_1 = (TP+TN)/(TP+FP+FN+TN)
print("Overall accuracy:",ACC_bin2_1)

true positive rate: 0.9817391304347826
true negative rate: 0.982304347826087
positive predictive value: 0.7350260416666666
negative predictive value: 0.9990713717166357
false positive rate: 0.017695652173913043
false negative rate: 0.018260869565217393
false discovery rate: 0.2649739583333333
Overall accuracy: 0.9822774327122153


### BIN3: 26. <= mu_g<= 27

In [54]:
# Binned test set
# Only real data
X_test_bin3_1 = np.concatenate((X_test_art3,X1_test_bin3)) 
y_test_bin3_1 = np.concatenate((y_test_art3,y1_test_bin3))
# Only simulation data
X_test_bin3_2 = np.concatenate((X_test_art3,X2_test_bin3)) 
y_test_bin3_2 = np.concatenate((y_test_art3,y2_test_bin3))

X_test_bin3_1 = scaler.transform(X_test_bin3_1)
X_test_bin3_2 = scaler.transform(X_test_bin3_2)

# Predict on the test set
y_pred_bin3_1 = model_rf_fin.predict(X_test_bin3_1)
y_pred_bin3_2 = model_rf_fin.predict(X_test_bin3_2)

print(len(X_test_art3),len(X1_test_bin3),len(X2_test_bin3))

5700 285 285


In [55]:
print("Precision (purity):",precision_score(y_test_bin3_1,y_pred_bin3_1))
print("Recall (completeness):",recall_score(y_test_bin3_1,y_pred_bin3_1))
print("Balanced accuracy:", balanced_accuracy_score(y_test_bin3_1,y_pred_bin3_1))

Precision (purity): 0.6923076923076923
Recall (completeness): 0.8842105263157894
Balanced accuracy: 0.9322807017543859


In [56]:
print("Precision (purity):",precision_score(y_test_bin3_2,y_pred_bin3_2))
print("Recall (completeness):",recall_score(y_test_bin3_2,y_pred_bin3_2))
print("Balanced accuracy:", balanced_accuracy_score(y_test_bin3_2,y_pred_bin3_2))

Precision (purity): 0.7128205128205128
Recall (completeness): 0.9754385964912281
Balanced accuracy: 0.9778947368421053


In [57]:
rate_bin3_1 = rates(y_test_bin3_1,y_pred_bin3_1)
rate_bin3_2 = rates(y_test_bin3_2,y_pred_bin3_2)

print("TN   FN   TP   FP")
print(rate_bin3_1)
print(rate_bin3_2)

TN   FN   TP   FP
[5588.   33.  252.  112.]
[5588.    7.  278.  112.]


In [58]:
TN = rate_bin3_1[0]
FN = rate_bin3_1[1]
TP = rate_bin3_1[2]
FP = rate_bin3_1[3]

# Sensitivity, hit rate, recall, or true positive rate
TPR_bin3_1 = TP/(TP+FN)
print("true positive rate:",TPR_bin3_1)
# Specificity or true negative rate
TNR_bin3_1 = TN/(TN+FP) 
print("true negative rate:",TNR_bin3_1)
# Precision or positive predictive value
PPV_bin3_1 = TP/(TP+FP)
print("positive predictive value:",PPV_bin3_1)
# Negative predictive value
NPV_bin3_1 = TN/(TN+FN)
print("negative predictive value:",NPV_bin3_1)
# Fall out or false positive rate
FPR_bin3_1 = FP/(FP+TN)
print("false positive rate:",FPR_bin3_1)
# False negative rate
FNR_bin3_1 = FN/(TP+FN)
print("false negative rate:",FNR_bin3_1)
# False discovery rate
FDR_bin3_1 = FP/(TP+FP)
print("false discovery rate:",FDR_bin3_1)

# Overall accuracy
ACC_bin3_1 = (TP+TN)/(TP+FP+FN+TN)
print("Overall accuracy:",ACC_bin3_1)

true positive rate: 0.8842105263157894
true negative rate: 0.9803508771929824
positive predictive value: 0.6923076923076923
negative predictive value: 0.9941291585127201
false positive rate: 0.019649122807017545
false negative rate: 0.11578947368421053
false discovery rate: 0.3076923076923077
Overall accuracy: 0.9757727652464494


In [ ]:
kihana@uchicago.edu - Kihana Wilson